#!/usr/bin/env python3
"""Generate a README.md index from H1 headings of NN-kebab-case.md files in a directory.

Usage:
    python generate_index.py --dir skills/ --output skills/README.md --title "Skills"
    python generate_index.py --dir docs/ --output docs/README.md --title "Docs"

The generated README has a marker comment at the top so it can be safely overwritten.
Exit 0 if the file is up-to-date or was rewritten; exit 1 on user error.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

MARKER = "<!-- AUTO-GENERATED by scripts/generate_index.py - do not edit manually -->"

NN_RE = re.compile(r"^(\d{2})-([a-z0-9-]+)\.md$")
H1_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)


def extract_h1(path: Path) -> str | None:
    """Read first H1 of a markdown file."""
    try:
        content = path.read_text(encoding="utf-8")
    except OSError:
        return None
    m = H1_RE.search(content)
    if not m:
        return None
    h1 = m.group(1).strip()
    h1 = re.sub(r"^\d{2}\s*[-]\s*", "", h1)
    return h1


def build_index(folder: Path, title: str, intro: str = "", footer: str = "") -> str:
    rows: list[tuple[str, str, str]] = []
    for f in sorted(folder.iterdir()):
        if not f.is_file() or f.name == "README.md":
            continue
        m = NN_RE.match(f.name)
        if not m:
            continue
        num = m.group(1)
        h1 = extract_h1(f) or f.stem
        rows.append((num, h1, f.name))

    lines: list[str] = [MARKER, f"# {title}", ""]
    if intro:
        lines.append(intro)
        lines.append("")
    lines.extend(["| # | Name |", "|---|---|"])
    for num, h1, fname in rows:
        lines.append(f"| {num} | [{h1}]({fname}) |")
    lines.append("")
    if footer:
        lines.append(footer)
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dir", required=True, type=Path, help="Directory of NN-*.md files to index")
    parser.add_argument("--output", required=True, type=Path, help="Output README path")
    parser.add_argument("--title", required=True, help="H1 title for the generated README")
    parser.add_argument("--intro", default="", help="Optional intro paragraph")
    parser.add_argument("--footer", default="", help="Optional footer markdown")
    args = parser.parse_args()

    folder: Path = args.dir
    if not folder.is_dir():
        print(f"ERROR: not a directory: {folder}", file=sys.stderr)
        return 1

    new_content = build_index(folder, args.title, args.intro, args.footer)
    target: Path = args.output
    target.parent.mkdir(parents=True, exist_ok=True)
    old = target.read_text(encoding="utf-8") if target.exists() else ""
    if old.strip() == new_content.strip():
        print(f"up-to-date: {target}")
        return 0
    target.write_text(new_content, encoding="utf-8")
    print(f"wrote: {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
